### ISSUE TITLE
Compilation error: main.go:36:35: undefined: assetFS

### ISSUE THREAD

**Issue by doron-cohen** [egeozcan/json-tail#1]
While trying to compile and install from source I got this error:

```
❯ GOBIN=/usr/local/bin/ go get github.com/egeozcan/json-tail
# github.com/egeozcan/json-tail
../../.cache/go/src/github.com/egeozcan/json-tail/main.go:36:35: undefined: assetFS
```

**Comment by egeozcan** [comment]
Hi, you need to clone the repo to build, because it needs to generate assets. You'll need node.js. I'll update the readme for detailed instructions and keep this issue open until I do.

**Comment by egeozcan** [comment]
Switched assetFS to go embed, so the compilation should work, I still need to switch to esbuild so the installation can be very frictionless

**Comment by egeozcan** [comment]
it now uses go:embed
